apps/cat_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'cat'

urlpatterns = [
    url(r'^home$', views.home, name='home'),
    url(r'^log_out$', views.log_out, name='log_out'),
    url(r'^add_cat_page$', views.add_cat_page, name='add_cat_page'),
    url(r'^add_cat$', views.add_cat, name='add_cat'),
    url(r'^add_like/(?P<cat_id>\d+)$', views.add_like, name='add_like'),
    url(r'^remove_like/(?P<cat_id>\d+)$', views.remove_like, name='remove_like'),
    url(r'^edit_cat_page/(?P<cat_id>\d+)$', views.edit_cat_page, name='edit_cat_page'),
    url(r'^edit_cat/(?P<cat_id>\d+)$', views.edit_cat, name='edit_cat'),
    url(r'^delete_cat/(?P<cat_id>\d+)$', views.delete_cat, name='delete_cat'),
]

cats2/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='user')),
    url(r'^cat/', include('apps.cat_app.urls', namespace='cat')),
]

apps/cat_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..user_app.models import User

# Create your models here.
class CatManager(models.Manager):
    def create_cat(self, data, user):
        errors = {}
        if not data['name'] or not data['age']:
            errors['data'] = 'Field cant be empty'
        if len(errors):
            return errors
        else:
            return self.create(name=data['name'], age=data['age'], user=user)

    def update_cat(self, data, cat_id):
        errors = {}
        if not data['name'] or not data['age']:
            errors['data'] = 'Field cant be empty'
        if len(errors):
            return errors
        else:
            return self.filter(id=cat_id).update(name=data['name'], age=data['age'])

class LikeManager(models.Manager):
    def create_like(self, cat, user):
        if self.filter(cat=cat, user=user):
            return False
        else:
            return self.create(cat=cat, user=user)


class Cat(models.Model):
    name = models.CharField(max_length=25)
    age = models.CharField(max_length=25)
    user = models.ForeignKey(User, related_name='cats')
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = CatManager()
    def cat_likes_user(self):
        users = []
        likes = Like.objects.filter(cat=self)
        for like in likes:
            users.append(like.user)
        return users

class Like(models.Model):
    cat = models.ForeignKey(Cat, related_name='cat_likes')
    user = models.ForeignKey(User, related_name='user_likes')
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = LikeManager()

apps/cat_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from ..user_app.models import User
from .models import Cat, Like

# Create your views here.
def home(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        context = {'user': user, 'cats': Cat.objects.all()}
        return render(request, 'cat_app/home.html', context)
    else:
        return redirect('user:index')

def log_out(request):
    request.session.flush()
    return redirect('user:index')

def add_cat_page(request):
    if 'user_id' in request.session:
        return render(request, 'cat_app/add_cat.html')
    else:
        return redirect('user:index')

def add_cat(request):
    user = User.objects.get(id=request.session['user_id'])
    entry = Cat.objects.create_cat(request.POST, user)
    if not type(entry) is dict:
        return redirect('cat:home')
    else:
        if 'data' in entry:
            messages.add_message(request, messages.INFO, entry['data'], extra_tags='data')
        return redirect('cat:add_cat_page')

def add_like(request, cat_id):
    user = User.objects.get(id=request.session['user_id'])
    cat = Cat.objects.get(id=cat_id)
    entry = Like.objects.create_like(cat, user)
    return redirect('cat:home')

def remove_like(request, cat_id):
    user = User.objects.get(id=request.session['user_id'])
    cat = Cat.objects.get(id=cat_id)
    Like.objects.filter(cat=cat, user=user).delete()
    return redirect('cat:home')


def edit_cat_page(request, cat_id):
    if 'user_id' in request.session:
        context = {'cat': Cat.objects.get(id=cat_id), }
        return render(request, 'cat_app/edit_cat.html', context)
    else:
        return redirect('user:index')

def edit_cat(request, cat_id):
    entry = Cat.objects.update_cat(request.POST, cat_id)
    if not type(entry) is dict:
        return redirect('cat:home')
    else:
        if 'data' in entry:
            messages.add_message(request, messages.INFO, entry['data'], extra_tags='data')
        return redirect(reverse('cat:edit_cat_page', kwargs={'cat_id': cat_id}))

def delete_cat(request, cat_id):
    Cat.objects.get(id=cat_id).delete()
    return redirect('cat:home')

apps/cat_app/templates/cat_app/add_cat.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Add cat here</h2>
    <form  action="{% url 'cat:add_cat' %}" method="post">
      {% csrf_token %}
      <input type="text" name="name" placeholder="cat name"><p></p>
      <input type="text" name="age" placeholder="age"><p></p>
      <input type="submit" value="Add Cat"><p></p>
      {% if messages %}
        {% for message in messages %}
          {% if 'data' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </form>
  </body>
</html>

apps/cat_app/templates/cat_app/edit_cat.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Edit your cat bio</h2>
    <form  action="{% url 'cat:edit_cat' cat_id=cat.id %}" method="post">
      {% csrf_token %}
      <input type="text" name="name" value="{{cat.name}}"><p></p>
      <input type="text" name="age" value="{{cat.age}}"><p></p>
      <input type="submit" value="Update"><p></p>
      {% if messages %}
        {% for message in messages %}
          {% if 'data' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </form>
  </body>
</html>

apps/cat_app/templates/cat_app/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
      table{
        border-collapse: collapse;
      }
      table, tr, td {
          padding: 5px;
          border: 1px solid black;
      }
    </style>
  </head>
  <body>
    <h2>Welcome {{user.first_name}}</h2>
    <p><a href="{% url 'cat:log_out' %}">Log Out</a></p>
    <p><a href="{% url 'cat:add_cat_page' %}">Add Cat</a></p>
    <table>
      <th>ID
        <td>NAME</td>
        <td>AGE</td>
        <td>LIKES</td>
        <td>ACTION</td>
      </th>
      {% for cat in cats %}
      <tr>
        {% if cat.user.id == user.id %}
          <td>{{cat.id}}</td>
          <td>{{cat.name}}</td>
          <td>{{cat.age}}</td>
          <td>{{cat.cat_likes.count}}</td>
          <td><a href="{% url 'cat:edit_cat_page' cat_id=cat.id %}">Edit</a>  <a href="{% url 'cat:delete_cat' cat_id=cat.id %}">Delete</a></td>
        {% else %}
          {% if user in cat.cat_likes_user %}
            <td>{{cat.id}}</td>
            <td>{{cat.name}}</td>
            <td>{{cat.age}}</td>
            <td>{{cat.cat_likes.count}}</td>
            <td><a href="{% url 'cat:remove_like' cat_id=cat.id %}">Unlike</a></td>
          {% else %}
            <td>{{cat.id}}</td>
            <td>{{cat.name}}</td>
            <td>{{cat.age}}</td>
            <td>{{cat.cat_likes.count}}</td>
            <td><a href="{% url 'cat:add_like' cat_id=cat.id %}">Like</a></td>
          {% endif %}
        {% endif %}
      </tr>
      {% endfor %}
    </table>
  </body>
</html>