apps/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'user'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign_up$', views.sign_up_test, name='sign_up_test'),
    url(r'^log_in$', views.log_in_test, name='log_in_test'),
]

cats2/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='user')),
    url(r'^cat/', include('apps.cat_app.urls', namespace='cat')),
]

apps/user_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt, re
EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Create your models here.
class UserManager(models.Manager):
    def create_user(self, data):
        errors = {}
        if not data['first_name'] or len(data['first_name']) < 2 or not data['last_name'] or len(data['last_name']) < 2:
            errors['name'] = 'Invalid Name'
        if not data['email'] or not EMAIL_REGEX.match(data['email']):
            errors['email'] = 'Invalid Email'
        if self.filter(email=data['email']):
            errors['email_exist'] = 'Email already exist'
        if not data['password'] or len(data['password']) < 4:
            errors['password'] = 'Invalid Password'
        if data['password'] != data['confirm_password']:
            errors['confirm_password'] = 'Password doesnt match'
        if len(errors):
            return errors
        else:
            hash_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return self.create(first_name=data['first_name'], last_name=data['last_name'], email=data['email'], password=hash_password)


    def validate_user(self, data):
        errors = {}
        if self.filter(email=data['email']):
            user = self.get(email=data['email'])
            if not data['password']:
                errors['password'] = 'Invalid Password'
            else:
                hash_password = bcrypt.hashpw(data['password'].encode(), user.password.encode())
                if hash_password == user.password:
                    return user
                else:
                    errors['password'] = 'Invalid Password'
        else:
            errors['email'] = 'Invalid Email'
        return errors               



class User(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.CharField(max_length=25)
    password = models.CharField(max_length=25)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/user_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
    return render(request, 'user_app/index.html')

def sign_up_test(request):
    entry = User.objects.create_user(request.POST)
    if not type(entry) is dict:
        request.session['user_id'] = entry.id
        return redirect('cat:home')
    else:
        if 'name' in entry:
            messages.add_message(request, messages.INFO, entry['name'], extra_tags='sign_up')
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='sign_up')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='sign_up')
        if 'confirm_password' in entry:
            messages.add_message(request, messages.INFO, entry['confirm_password'], extra_tags='sign_up')
        if 'email_exist' in entry:
            messages.add_message(request, messages.INFO, entry['email_exist'], extra_tags='sign_up')
        return redirect('user:index')

def log_in_test(request):
    entry = User.objects.validate_user(request.POST)
    if not type(entry) is dict:
        request.session['user_id'] = entry.id
        return redirect('cat:home')
    else:
        if 'email' in entry:
            messages.add_message(request, messages.INFO, entry['email'], extra_tags='log_in')
        if 'password' in entry:
            messages.add_message(request, messages.INFO, entry['password'], extra_tags='log_in')
        return redirect('user:index')

apps/user_app/templates/user_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
    div{
        display: inline-block;
        margin-right: 20px;
      }
    </style>
  </head>
  <body>
    <div class="">
      <h2>Sign Up</h2>
      <form  action="{% url 'user:sign_up_test' %}" method="post">
        {% csrf_token %}
        <input type="text" name="first_name" placeholder="first name"><p></p>
        <input type="text" name="last_name" placeholder="last name"><p></p>
        <input type="email" name="email" placeholder="email address"><p></p>
        <input type="text" name="password"  placeholder="password"><p></p>
        <input type="text" name="confirm_password"  placeholder="confirm password"><p></p>
        <input type="submit" value="Register">
      </form>
      {% if messages %}
        {% for message in messages %}
          {% if 'sign_up' in message.tags %}
             <p>{{message}}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>

    <div>
      <h2>Log In</h2>
      <form  action="{% url 'user:log_in_test' %}" method="post">
        {% csrf_token %}
        <input type="email" name="email" placeholder="email address"><p></p>
        <input type="text" name="password" placeholder="password"><p></p>
        <input type="submit" value="Log In"><p></p>
        {% if messages %}
          {% for message in messages %}
            {% if 'log_in' in message.tags %}
               <p>{{message}}</p>
            {% endif %}
          {% endfor %}
        {% endif %}
      </form>
    </div>
  </body>
</html>